---
# playbook to ensure osx configs
- name: set sane OSX config defaults
  hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - osx.config
    
  tags:
    - osx
...
