---
# playbook to ensure homebrew installs
- name: Homebrew some beers
  hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - brew.install
    
  tags:
    - brews
...
