---
# main file to kick off tasks from
  
  - name: Homebrew some beers
    hosts: 127.0.0.1
    connection: local
    remote_user: "{{ mac_username }}"
    roles:
      - brew.install
    tags:
      - brews

  - name: Homebrew into some casks
    hosts: 127.0.0.1
    connection: local
    remote_user: "{{ mac_username }}"
    roles:
      - cask.install
    tags:
      - casks

  - name: Add .dotfiles 
    hosts: 127.0.0.1
    connection: local
    remote_user: "{{ mac_username }}"
    roles:
      - dotfile.config
    tags:
      - dotfiles

  - name: Setup AWS Cli tools
    hosts: 127.0.0.1
    connection: local
    remote_user: "{{ mac_username }}"
    roles:
      - awscli.install
    tags:
      - awscli