---
# main file to kick off tasks from
  
  - name: Homebrew some beers
    hosts: local
    connection: local
    roles:
      - brew.install
    tags:
      - brews

  - name: Homebrew into some casks
    hosts: local
    connection: local
    roles:
      - cask.install
    tags:
      - casks

  - name: Add .dotfiles 
    hosts: local
    connection: local
    roles:
      - dotfile.config
    tags:
      - dotfiles