---
# main file to kick off tasks from
  
  - name: Homebrew some beers
    hosts: 127.0.0.1
    connection: local
    roles:
      - brew.install
    tags:
      - brews

  - name: Homebrew into some casks
    hosts: 127.0.0.1
    connection: local
    roles:
      - cask.install
    tags:
      - casks

  - name: Set secure OSX config defaults
      hosts: 127.0.0.1
      connection: local
      roles:
        - osx.config
      tags:
        - osx

  - name: Add .dotfiles 
    hosts: 127.0.0.1
    connection: local
    roles:
      - dotfile.config
    tags:
      - dotfiles