---
# main file to kick off tasks from
  
  - vars_files:
    - passes

  - name: Homebrew some beers
    hosts: 127.0.0.1
    remote_user: "{{ mac_username }}"
    roles:
      - brew.install
    tags:
      - brews

  - name: Homebrew into some casks
    hosts: 127.0.0.1
    remote_user: "{{ mac_username }}"
    roles:
      - cask.install
    tags:
      - casks