---
# tasks file for cask.install

  - name: Update Homebrew
    homebrew:
      update_homebrew: yes

  - name: Install Brew Caskroom
    homebrew:
      name: cask
      state: present

  - name: Add the Casks
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - alfred
      - appcleaner
      - backblaze
      - caffeine
      - chicken
      - cyberduck
      - do-not-disturb
      - firefox
      - google-chrome
      - handbrake
      - imageoptim
      - istumbler
      - iterm2
      - keepassxc
      - keka
      - kindle
      - knockknock
      - little-snitch
      - lulu
      - oversight
      - mist
      - owasp-zap
      - ricochet
      - signal
      - slack
      - spectacle
      - spotify
      - transmission
      - transmit
      - vlc
      - whatsapp
      - wireshark
...
