---
# tasks file for cask.install

  - name: Update Homebrew
    homebrew:
      update_homebrew=yes

  - name: Install Brew Caskroom
    homebrew:
      name=cask
      state=present

#  - name: Setup the Caskroom
#    file:
#      path=/etc/Caskroom
#      owner="{{ mac_username }}"
#      group=wheel
#      mode=0744
#
#  - name: Touch zshrc
#    file:
#      path=/Users/{{ mac_username }}/.zshrc
#      owner="{{ mac_username }}"
#      state=touch
#  
#  - name: Change the cask directory to /Applications
#    lineinfile:
#      dest=~/.zshrc
#      insertafter=EOF
#      state=present
#      line="export HOMEBREW_CASK_OPTS=\"--appdir=/Applications --caskroom=/etc/Caskroom\""
#
#  - name: Source .zshrc
#    shell: source /Users/{{ mac_username }}/.zshrc

  - name: Add the Casks
    homebrew_cask:
      name={{ item }}
      state=present
    with_items:
      - alfred
      - appcleaner
      - atom
      - backblaze
      - caffeine
      - charles
      - chicken
      - chrome-devtools
      - cord
      - cyberduck
      - dash
      - dayone-cli
      - docker
      - dropbox
      - dupin
      - exiftool
      - ffmpegx
      - flux
      - forklift
      - gimp
      - github
      - google-chrome
      - google-cloud-sdk
      - gpgtools
      - gramps
      - imageoptim
      - iphone-backup-extractor
      - istumbler
      - iterm2
      - keepassxc
      - keka
      - keybase
      - kindle
      - kismac
      - little-snitch
      - macdown
      - mactex
      - mist
      - mou
      - namebench
      - nmap
      - openemu
      - owasp-zap
      - ricochet
      - signal
      - slack
      - spotify
      - thunderbird
      - transmission
      - transmit
      - tunnelblick
      - unetbootin
      - vagrant
      - vagrant-manager
      - vlc
      - whatsapp
      - wireshark
      - xccello
...