---
# tasks file for cask.install

  - name: Update Homebrew
    homebrew:
      update_homebrew=yes

  - name: Install Brew Caskroom
    homebrew:
      name: cask
      state: present

  - name: Add the Casks
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - alfred
      - appcleaner
      - atom
      - backblaze
      - caffeine
      - charles
      - chicken
      - chrome-devtools
      - cord
      - cyberduck
      - dash
      - dayone-cli
      - docker
      - dropbox
      - dupin
      - exiftool
      - ffmpegx
      - flux
      - forklift
      - gimp
      - github
      - google-chrome
      - google-cloud-sdk
      - gpgtools
      - gramps
      - imageoptim
      - iphone-backup-extractor
      - istumbler
      - iterm2
      - keepassxc
      - keka
      - keybase
      - kindle
      - kismac
      - little-snitch
      - macdown
      - mactex
      - mist
      - mou
      - namebench
      - nmap
      - openemu
      - owasp-zap
      - ricochet
      - signal
      - slack
      - spotify
      - thunderbird
      - transmission
      - transmit
      - tunnelblick
      - unetbootin
      - vagrant
      - vagrant-manager
      - vlc
      - whatsapp
      - wireshark
      - xccello
      - zoomus
...